---

- hosts: localhost
  roles:
    - packages
  tasks:

    - name: Install Goss
      raw: "curl -fsSL https://goss.rocks/install | sh"
      become: true

    - name: Install nginx
      yum:
        name: nginx
        state: present
